In [3]:
import pandas as pd
import numpy as np

In [ ]:
# pandas Series
marks = [85, 90, 78, 65]
# print(pd.Series(marks))

marks = [85, 90, 78, 65]
# print(pd.Series(marks,index=["a", "b", "c", "d"]))

In [ ]:
# create series by tuple
t=("a", "b", "c")
# print(pd.Series(t))

In [ ]:
# create series by using dic
d={"a":12, "b":51, "c":56}
print(pd.Series(d))

In [ ]:
# create series by using array
d=np.array([40, 50, 60])
print(pd.Series(d))

In [1]:

# create Data Frame using dic
data = {'name':['a', 'b', 'c'],'mark':[85,90,74], 'city':['ahm','dwarika','surat']}
df=pd.DataFrame(data)
df

  name  mark     city
0    a    85      ahm
1    b    90  dwarika
2    c    74    surat

In [4]:
# create data frame by using list
data=[['a', 80],['b', 90],['c', 100]]
df=pd.DataFrame(data,columns=['name','marks'],index=['a','b','c'])
df

  name  marks
a    a     80
b    b     90
c    c    100

In [5]:
# create dataframe by using lis of dic
data = [{'name':'a','mark':80},{'name':'b','mark':90},{'name':'c','mark':100}]
df=pd.DataFrame(data)
df

  name  mark
0    a    80
1    b    90
2    c   100

In [14]:
#create dic uing pandas series
s1=pd.Series([1,2,3])
s2=pd.Series([4,5,6])

df=pd.DataFrame({"col1":s1,"col2":s2})
df

   col1  col2
0     1     4
1     2     5
2     3     6

In [18]:
#create dic uing pandas series
s1=pd.Series([1,2,3])
s2=pd.Series([4,5,6])

df=pd.DataFrame({"col1":s1,"col2":s2})
df.set_index("col2")

      col1
col2
4        1
5        2
6        3

In [24]:
# read csv file
df=pd.read_csv("auto-mpg.csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [25]:
# first number(5) of rows
df.head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [28]:
# last number(5) of rows
df.tail(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [29]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [32]:
df.shape # output => tuple

(398, 9)

In [35]:
# loc function
# print data given range
#row wise data fiter
df.loc[5:7]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii

In [42]:
df[['mpg','weight']]

      mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
393  27.0    2790
394  44.0    2130
395  32.0    2295
396  28.0    2625
397  31.0    2720

[398 rows x 2 columns]

In [46]:
# c=5 r=10

dff=df.tail(10)
dff[['weight','acceleration','model year','origin','car name']]
#df = df[['weight','acceleration','model year','origin','car name']].tail(10)

     weight  acceleration  model year  origin                    car name
388    2585          14.5          82       1  chrysler lebaron medallion
389    2835          14.7          82       1              ford granada l
390    2665          13.9          82       3            toyota celica gt
391    2370          13.0          82       1           dodge charger 2.2
392    2950          17.3          82       1            chevrolet camaro
393    2790          15.6          82       1             ford mustang gl
394    2130          24.6          82       2                   vw pickup
395    2295          11.6          82       1               dodge rampage
396    2625          18.6          82       1                 ford ranger
397    2720          19.4          82       1                  chevy s-10

In [49]:
# loc => include end print
# iloc => end -1
df[['weight','acceleration','model year','origin','car name']].loc[199:207]

     weight  acceleration  model year  origin            car name
199    3651          17.7          76       1      dodge aspen se
200    3574          21.0          76       1   ford granada ghia
201    3645          16.2          76       1  pontiac ventura sj
202    3193          17.8          76       1       amc pacer d/l
203    1825          12.2          76       2   volkswagen rabbit
204    1990          17.0          76       3        datsun b-210
205    2155          16.4          76       3      toyota corolla
206    2565          13.6          76       1          ford pinto
207    3150          15.7          76       2           volvo 245

In [57]:
# iloc[row,column]
# loc => include end print
# iloc => end -1

df.iloc[3:9,:3]

    mpg  cylinders  displacement
3  16.0          8         304.0
4  17.0          8         302.0
5  15.0          8         429.0
6  14.0          8         454.0
7  14.0          8         440.0
8  14.0          8         455.0

In [68]:
# cols => 3,5,7,9
#rows => 11,14,17,20,23,26,29,32
df.iloc[11:33:3,2:10:2]

    displacement  weight  model year               car name
11         340.0    3609          70     plymouth 'cuda 340
14         113.0    2372          70  toyota corona mark ii
17         200.0    2587          70          ford maverick
20         110.0    2672          70            peugeot 504
23         121.0    2234          70               bmw 2002
26         307.0    4376          70              chevy c20
29          97.0    2130          71           datsun pl510
32          98.0    2046          71             ford pinto